name: country_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  flutter_svg: ^2.0.1
  shared_preferences: ^2.0.17
  url_launcher: ^6.1.10
  image_picker: ^0.8.6+4
  cached_network_image: ^3.2.3
  flutter_linkify: ^5.0.2
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  http: ^0.13.3
  sqflite: ^2.0.0
  path: ^1.8.0
  dio: ^4.0.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Italic.ttf
          style: italic
